apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.1.3

    helm:
      values: |
        controller:
          serviceType: ClusterIP

          admin:
            username: admin
            password: admin123

          serviceAccount:
            create: false
            name: jenkins

          # 🔥 disable storage completely
          persistence:
            enabled: false

          # 🔥 avoid permission issues
          securityContext:
            runAsUser: 0
            fsGroup: 0

          # 🔥 keep it light
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"

destination:
  server: https://kubernetes.default.svc
  namespace: jenkins

syncPolicy:
  automated:
    prune: true
    selfHeal: true

  syncOptions:
    - CreateNamespace=true
