apiVersion: v1
kind: Secret
metadata:
  name: devops-platform-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  url: https://github.com/git-ashu/devops-platform.git
  type: git
